# Site
name: "Unser Gartenblog"
title: "Gartenblog"
description: "Ein Blog über unseren Garten, Pflanzen und Natur."
logo: 'assets/images/logo.jpg'
favicon: 'assets/images/logo.jpg'
#baseurl: /
google_analytics: ''
#disqus: 'demowebsite'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  cd:
    name: cd
    display_name: C.D
#    gravatar: e56154546cf4be74e393c62d1ae9f9d4
#    email: wowthemesnet@gmail.com
#    web: https://www.wowthemes.net
#    twitter: https://twitter.com/wowthemesnet
    description: "Gartenliebhaber und Bloggerneuling. Hier teile ich meine Erfahrungen und Tipps rund um den Garten."
#  john:
#    name: John
#    display_name: John    
#    avatar: 'assets/images/avatar.png'
#    gravatar: b1cc14991db7a456fcd761680bbc8f81
#    email: wowthemesnet@gmail.com
#    web: https://www.wowthemes.net
#    twitter: https://twitter.com/wowthemesnet
#    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-8491194385164292"
adsense-data-ad-slot: "f08c47fec0942fa0"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
